import {
  Pyramid,
  X,
  XCircle,
  LogIn,
  Menu,
  ArrowLeft,
  ArrowRight,
  ArrowLeftCircle,
  ArrowRightCircle,
  Lock,
  ClipboardMinus,
  FileInput,
  Loader2,
  ChevronLeft,
  AlignRight,
  Eye,
  EyeOff,
  Calendar
} from "lucide-react";

export const Icons = {
  logo: Pyramid,
  close: X,
  closeCircle: XCircle,
  login: LogIn,
  menu: Menu,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowLeftCircle: ArrowLeftCircle,
  arrowRightCircle: ArrowRightCircle,
  lock: Lock,
  clipboardMinus: ClipboardMinus,
  fileInput: FileInput,
  loader: Loader2,
  chevronLeft: ChevronLeft,
  alignRight: AlignRight,
  eye: Eye,
  eyeOff: EyeOff,
  calendar: Calendar,
};
